[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[functions."trilhas"]
  included_files = ["data/**.json"]
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[[redirects]]
  force = true
  from = "/trilhas"
  status = 200
  to = "/.netlify/functions/trilhas"
[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"
